branch-defaults:
  feat/prod:
    environment: null
    group_suffix: null
global:
  application_name: agilit-server
  branch: feat/prod
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: origin
  sc: git
  workspace_type: Application
